Repository RodolphoVSantoro/j-xadrez, pull requests merged in 2023-06, with the labels that each got.

#82 Documentacao dos métodos da Máquina de Regras e IA
  Tela.java
  maquinaDeRegras/IA.java
  maquinaDeRegras/MaquinaDeRegras.java
  maquinaDeRegras/Tabuleiro.java
  pecas/Peca.java
  pecas/Rei.java
Labels: documentation

#83 Adição da descrição dos métodos da interface
  Tela.java
  events/Input.java
  menu/EndGameScreen.java
  menu/Promocao.java
  utils/LeitorImagem.java
Labels: documentation

#71 Movimentos Especiais
  Tela.java
  events/Input.java
  maquinaDeRegras/Historico.java
  maquinaDeRegras/IA.java
  maquinaDeRegras/MaquinaDeRegras.java
  maquinaDeRegras/Movimento.java
  maquinaDeRegras/Tabuleiro.java
  pecas/Bispo.java
  pecas/Cavalo.java
  pecas/Dama.java
  pecas/Peao.java
  pecas/Peca.java
  pecas/Rei.java
  pecas/Torre.java
  utils/Posicao.java
Labels: feature

#86 fix: removendo a chamada do construtor descontinuado do Historico()
  .vscode/launch.json
  EventsExample.java
  maquinaDeRegras/MaquinaDeRegras.java
Labels: hotfix

#78 Condicoes empate
  Tela.java
  events/Input.java
  maquinaDeRegras/IA.java
  maquinaDeRegras/MaquinaDeRegras.java
  maquinaDeRegras/Tabuleiro.java
  pecas/Peca.java
  pecas/Rei.java
Labels: feature

#87 Wip/GitHub actions testing
  Makefile
  Tela.java
  events/Input.java
  events/PrintaHistorico.java
  maquinaDeRegras/IA.java
  maquinaDeRegras/MaquinaDeRegras.java
  menu/Botao.java
  menu/EndGameScreen.java
  pecas/Bispo.java
  pecas/Cavalo.java
  pecas/Dama.java
  pecas/Peao.java
  pecas/Rei.java
  pecas/Torre.java
  tests/TestRunner.java
  tests/config/SetupPecasTest.java
  tests/config/SetupTabuleiroTest.java
  tests/maquinaDeRegras/IATest.java
  utils/Posicao.java
Labels: tests

#88 Feature/promocao
  .vscode/launch.json
  Tela.java
  assets/images/pecas/branco_center/bispo.png
  assets/images/pecas/branco_center/cavalo.png
  assets/images/pecas/branco_center/dama.png
  assets/images/pecas/branco_center/torre.png
  assets/images/pecas/preto_center/bispo.png
  assets/images/pecas/preto_center/cavalo.png
  assets/images/pecas/preto_center/dama.png
  assets/images/pecas/preto_center/torre.png
  assets/images/promocao.png
  events/Input.java
  maquinaDeRegras/IA.java
  maquinaDeRegras/MaquinaDeRegras.java
  menu/EndGameScreen.java
  menu/Promocao.form
  menu/Promocao.java
  pecas/Bispo.java
  pecas/Cavalo.java
  pecas/Dama.java
  utils/ArmazemInt.java
  utils/LeitorImagem.java
  utils/Posicao.java
Labels: feature

#90 hotfix: removendo construtor duplicado
  utils/Posicao.java
Labels: hotfix

#89 Feature/capturadas
  Tela.java
  events/Input.java
  maquinaDeRegras/IA.java
  maquinaDeRegras/MaquinaDeRegras.java
  maquinaDeRegras/Tabuleiro.java
  pecas/Peca.java
  tests/maquinaDeRegras/IATest.java
Labels: feature

#91 fix: tela piscando - portando de canvas pra jpanel
  Tela.java
  events/Input.java
  pecas/Peca.java
Labels: cosmetics

#93 feature: setting difficulty screen
  .vscode/launch.json
  assets/images/dificuldade.png
  maquinaDeRegras/MaquinaDeRegras.java
  menu/Dificuldade.form
  menu/Dificuldade.java
  menu/Menu.java
Labels: feature

#97 hotfix: adicionando tela final de empate
  Tela.java
  maquinaDeRegras/IA.java
  menu/EndGameScreen.java
  menu/Menu.java
Labels: hotfix
